/** Class used to record the details of a tenant
 *  @author Daniel Bolarinwa
 */

public class Caller {
    private String id; // TODO: implement autogenerated/incremented id!!!
    private String name;
    private int age;
    private String address;
    
    public Caller(String nameIn, int ageIn, String addressIn) {
        name = nameIn;
        age = ageIn;
        address = addressIn;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    public String getAddress() {
        return address;
    }

    public void reportEmergency(Emergency emergencyIn) {
        EmergencyList.addEmergency(id, emergencyIn); // reports a given emergency
    }

    @Override
	public String toString()
   {
            return name+", "+age +", "+address;
   }
}
